-- Create featured_artists table (for the "Meet Our Artists" section on /artists page)
CREATE TABLE IF NOT EXISTS featured_artists (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  image TEXT NOT NULL,
  bio TEXT NOT NULL,
  performances VARCHAR(50) NOT NULL DEFAULT '100+',
  rating DECIMAL(2,1) NOT NULL DEFAULT 4.8,
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_featured_artists_active ON featured_artists(is_active);
CREATE INDEX IF NOT EXISTS idx_featured_artists_sort ON featured_artists(sort_order);

-- Insert all featured artists
INSERT INTO featured_artists (id, name, category, genre, image, bio, performances, rating, sort_order) VALUES
(1, 'Khullar G', 'Singer & Rapper', 'Punjabi Rapper & Singer',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=1000&fit=crop&crop=face',
  'Dynamic Punjabi rapper and singer known for his energetic performances and contemporary style. Brings the perfect blend of traditional Punjabi music with modern rap elements.',
  '200+', 4.8, 1),
(2, 'Kamakshi', 'Singer', 'Bollywood & Punjabi',
  'https://images.unsplash.com/photo-1494790108755-2616c9c0e8e3?w=800&h=1000&fit=crop&crop=face',
  'Versatile vocalist specializing in Bollywood and Punjabi music. Known for her soulful voice and captivating stage presence that mesmerizes audiences.',
  '300+', 4.9, 2),
(3, 'Ananya Mishra', 'Singer & Performer', 'Multi-Genre Performer',
  'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=1000&fit=crop&crop=face',
  'Talented singer and performer leading a 4-artist ensemble. Delivers powerful performances across multiple genres with exceptional vocal range and stage charisma.',
  '250+', 4.7, 3),
(4, 'Priyanka Mehar', 'Singer', 'Folk & Bollywood',
  '/priyanka-meher.png',
  'Accomplished folk and Bollywood singer with deep roots in traditional Indian music. Her performances beautifully blend classical folk traditions with contemporary Bollywood hits.',
  '350+', 4.8, 4),
(5, 'Sid K', 'Singer', 'Punjabi & Bollywood',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop&crop=face',
  'Popular Punjabi and Bollywood singer known for his versatile voice and crowd-pleasing performances. Brings high energy and authentic musical experience to every event.',
  '400+', 4.9, 5),
(6, 'Vijay Jammer', 'Singer', 'Sufi & Bollywood',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=1000&fit=crop&crop=face',
  'Soulful Sufi and Bollywood singer with a mesmerizing voice that touches hearts. Specializes in creating intimate, spiritual musical experiences through his performances.',
  '300+', 4.8, 6),
(7, 'Yashraj', 'Rapper', 'Hip-Hop & Rap',
  'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=800&h=1000&fit=crop&crop=face',
  'Rising star in the Indian rap scene known for his lyrical prowess and dynamic stage presence. Delivers high-energy performances that resonate with young audiences.',
  '150+', 4.7, 7),
(8, 'Khushboo Grewal', 'Singer', 'Bollywood Singer',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=1000&fit=crop&crop=face',
  'Renowned Bollywood playback singer with numerous hit songs to her credit. Her melodious voice and professional stage presence make her a favorite for premium events.',
  '500+', 4.9, 8),
(9, 'Sandeep Batraa', 'Singer & Performer', 'Bollywood Singer & Performer',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1000&fit=crop&crop=face',
  'Versatile Bollywood singer and performer with extensive experience in live entertainment. Known for his engaging performances and ability to connect with diverse audiences.',
  '600+', 4.8, 9),
(10, 'Charu Semwal', 'Singer & Performer', 'Bollywood Singer & Performer',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=1000&fit=crop&crop=face',
  'Accomplished Bollywood singer and performer available both as solo artist and with ensemble. Delivers captivating performances with professional excellence.',
  '450+', 4.9, 10),
(11, 'Jyotica Tangri', 'Playback Singer', 'Bollywood Singer',
  'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=800&h=1000&fit=crop&crop=face',
  'Popular Bollywood playback singer known for hit songs in major films. Her powerful voice and stage charisma make her performances unforgettable experiences.',
  '300+', 5.0, 11),
(12, 'Usha Uthup', 'Legendary Singer', 'Traditional Indian Melodies',
  'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=800&h=1000&fit=crop&crop=face',
  'Iconic Indian singer and cultural legend known for her distinctive voice and timeless melodies. A true treasure of Indian music with decades of memorable performances.',
  '1000+', 5.0, 12),
(13, 'Paradox', 'Music Group', 'Bollywood Mix',
  '/paradox.png',
  'Dynamic music group specializing in Bollywood remixes and contemporary sounds. Known for their innovative approach to popular music and electrifying live performances.',
  '200+', 4.8, 13),
(14, 'MC Square', 'Rapper', 'Hip-Hop Rapper',
  '/mcsquare.png',
  'Rising hip-hop sensation and winner of MTV Hustle. Known for his unique style, powerful lyrics, and ability to energize crowds with his dynamic rap performances.',
  '100+', 4.9, 14),
(15, 'Shaarib & Toshi', 'Music Directors', 'Bollywood Music Directors & Performers',
  'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=800&h=1000&fit=crop&crop=face',
  'Acclaimed Bollywood music director duo known for composing hit songs for major films. Available as 2-artist or 4-artist ensemble for exclusive performances.',
  '150+', 5.0, 15),
(16, 'Badshah', 'Celebrity Artist', 'Bollywood Singer & Punjabi Rapper',
  '/badshah.png',
  'Bollywood superstar and one of India''s most popular rappers. Known for chart-topping hits and electrifying performances that guarantee unforgettable entertainment experiences.',
  '500+', 5.0, 16);

COMMENT ON TABLE featured_artists IS 'Featured artists displayed on the /artists page';
